name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */12 * * *" # Updates every 12 hours
  workflow_dispatch:       # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update README with latest stats" || echo "No changes to commit"
          git push
